// Generated by LIBLAB | https://liblab.com

//go:build acceptance
// +build acceptance

package acceptance

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"path"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/terraform-provider-liblab/internal/provider"
)

func getTokenProviderConfig(serverUrl string) string {
	return fmt.Sprintf(`
		provider "liblab" {
        host = "%v"
        auth_token = "auth_token"
}

	`, serverUrl)
}

func setupTokenMockServer() *httptest.Server {
	db := make(map[string]*get_token_response.Token)
	server := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		if req.Method == http.MethodGet {
			Id := path.Base(req.URL.Path)
			get_token_response := db[Id]
			data, _ := json.Marshal(get_token_response)

			rw.Write(data)
			return
		}
		if req.Method == http.MethodPost {
			id := "id"

			get_token_response := get_token_response.Token{}

			bodyBytes, _ := io.ReadAll(req.Body)
			json.Unmarshal(bodyBytes, &get_token_response)

			get_token_response.SetId(id)
			data, _ := json.Marshal(get_token_response)

			db[id] = &get_token_response

			rw.Write(data)
			return
		}
		if req.Method == http.MethodPatch || req.Method == http.MethodPut {
			get_token_responseId := path.Base(req.URL.Path)

			if db[get_token_responseId] == nil {
				rw.Write([]byte("Error"))
				return
			}

			get_token_response := get_token_response.Token{}

			bodyBytes, _ := io.ReadAll(req.Body)
			json.Unmarshal(bodyBytes, &get_token_response)

			get_token_response.SetId(get_token_responseId)
			data, _ := json.Marshal(get_token_response)

			db[get_token_responseId] = &get_token_response

			rw.Write(data)
			return
		}
	}))

	return server
}

func TestAccliblabTokenResource(t *testing.T) {
	testAccProtoV6ProviderFactories := map[string]func() (tfprotov6.ProviderServer, error){
		"liblab": providerserver.NewProtocol6WithError(provider.New("test")()),
	}

	server := setupTokenMockServer()
	defer server.Close()
	providerConfig := getTokenProviderConfig(server.URL)

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create and Read
			{
				Config: providerConfig +
					`
resource "liblab_get_token_response" "example" {
    name = "My Token"

    expires_at = "My Token"

    scope = [
        "scope"
    ]

}

`,
				Check: resource.ComposeAggregateTestCheckFunc(
					// Extend this based on the model attributes
					resource.TestCheckResourceAttr("liblab_get_token_response.example", "name", "My Token"),
					resource.TestCheckResourceAttr("liblab_get_token_response.example", "expires_at", "My Token"),
					resource.TestCheckResourceAttr("liblab_get_token_response.example", "scope.0", "scope"),
				),
			},
		},
	})
}
