// Generated by LIBLAB | https://liblab.com

package client

import (
	"github.com/liblab-sdk/internal/configmanager"
	"github.com/liblab-sdk/pkg/clientconfig"
	"github.com/liblab-sdk/pkg/token"
)

type Client struct {
	Token   *token.TokenService
	manager *configmanager.ConfigManager
}

func NewClient(config clientconfig.Config) *Client {
	manager := configmanager.NewConfigManager(config)
	return &Client{
		Token:   token.NewTokenService(manager),
		manager: manager,
	}
}

func (c *Client) SetBaseUrl(baseUrl string) {
	c.manager.SetBaseUrl(baseUrl)
}

func (c *Client) SetAccessToken(accessToken string) {
	c.manager.SetAccessToken(accessToken)
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
