// Generated by LIBLAB | https://liblab.com

package configmanager

import "github.com/liblab-sdk/pkg/clientconfig"

type ConfigManager struct {
	Token clientconfig.Config
}

func NewConfigManager(config clientconfig.Config) *ConfigManager {
	return &ConfigManager{
		Token: config,
	}
}

func (c *ConfigManager) SetBaseUrl(baseUrl string) {
	c.Token.SetBaseUrl(baseUrl)
}

func (c *ConfigManager) SetAccessToken(accessToken string) {
	c.Token.SetAccessToken(accessToken)
}

func (c *ConfigManager) UpdateAccessToken(originalValue string, newValue string) {

	if c.Token.AccessToken != nil && *c.Token.AccessToken == originalValue {
		c.Token.SetAccessToken(newValue)
	}
}

func (c *ConfigManager) GetToken() *clientconfig.Config {
	return &c.Token
}
