// Generated by LIBLAB | https://liblab.com

package token

type CreateTokenRequest struct {
	Name      *string `json:"name,omitempty" required:"true"`
	Scope     []Scope `json:"scope,omitempty" required:"true"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
}

func (c *CreateTokenRequest) SetName(name string) {
	c.Name = &name
}

func (c *CreateTokenRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateTokenRequest) SetScope(scope []Scope) {
	c.Scope = scope
}

func (c *CreateTokenRequest) GetScope() []Scope {
	if c == nil {
		return nil
	}
	return c.Scope
}

func (c *CreateTokenRequest) SetExpiresAt(expiresAt string) {
	c.ExpiresAt = &expiresAt
}

func (c *CreateTokenRequest) GetExpiresAt() *string {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

type Scope string

const (
	SCOPE_SDK      Scope = "SDK"
	SCOPE_DOC      Scope = "DOC"
	SCOPE_BUILD    Scope = "BUILD"
	SCOPE_API      Scope = "API"
	SCOPE_ARTIFACT Scope = "ARTIFACT"
	SCOPE_ORG      Scope = "ORG"
)
